stages:
  preprocess:
    cmd: node scripts/preprocess.mjs
    deps:
      - data/ben-philips-housing-data/tenureqntl.csv
      - data/ben-philips-housing-data/hstress3.xlsx
    outs:
      - data/housing-data-clean/data.json
      - data/housing-data-clean/data.csv
